name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y mpich libmpich-dev
        pip install tox tox-gh-actions mpi4py
    - name: Test with tox
      run: tox
    - name: Test MPI
      run: |
        (cd tests; make mpi MPIARGS=)
        coverage combine
    - name: Coverage—Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
    - name: Coverage—Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coverage—Coveralls finishing
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
